validator: update kube dependencies to v1.23.4
kubernetes-csi/volume-data-source-validator pull request #21
Opened 2022-03-03 13:10 UTC by humblec

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

> /kind api-change

```release-note
Kuberenetes client dependencies are updated to v1.23 with this release
```

2022-03-03 13:11 UTC, humblec commented
/assign @bswartz

2022-03-03 14:56 UTC, bswartz requested changes

2022-03-03 14:58 UTC, humblec commented on go.mod
>  	k8s.io/component-base v0.22.0
Yep,its good to keep in parity, refreshed the PR @bswartz

2022-03-03 15:00 UTC, bswartz approved these changes
/approve
/lgtm

2022-03-04 11:29 UTC, humblec commented
On a refresh the `lgtm` was removed, @bswartz can you please bring back the same?

2022-03-04 18:46 UTC, bswartz approved these changes
/lgtm

2022-03-04 18:46 UTC, merged